meta:
  engine: 4.1.0
  name: martlet
  author: Thomas Stephan

units:
  # default ui settings
  $default_width: cx
  $default_height: cy
   
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4

points:
  key:
    padding: 1ky
    spread: 1kx
  zones.matrix:                                                                         
    rows:
      bottom:
      home:
      top:                            
    columns:
      outer:
        rows.bottom.skip: true
      pinky: 
        key.stagger: 0.5 ky
      ring:
        key.stagger: 7
      middle:
        key.stagger: 2
      index:
        key:
          stagger: -6
          #splay: -5
      inner:
        key:
          stagger: 2
          #splay: -10

  zones.thumb: 
    key:
      spread: kx + 4  
    anchor:
      ref: matrix_middle_bottom
      shift: [0.5 kx,-ky - 10]
    columns:
      left:
      middle:
        key:
          splay: -15
          stagger: -3
      right:
        key:
          splay: -16
          stagger: 2
          spread: kx + 4.5
          width: 1.5 kx
          rotate: 90

  rotate: -28
  mirror: &mirror
    ref: matrix_inner_top
    distance: 2 kx

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_right
          shift: [px, -py/2]
        - ref: thumb_right
          shift: [-px/2, -py/2]
        - ref: thumb_middle
          shift: [px/2, -py/2]
        - ref: thumb_left
          shift: [-px/2, -py/2]
        - ref: matrix_pinky_bottom
          shift: [px,-py/2]
        - ref: matrix_pinky_bottom
          shift: [-px/2,-py/2]
        - ref: matrix_outer_home
          shift: [-px/2,-py/2]
        - ref: matrix_outer_top
          shift: [-px/2, py/2]
        - ref: matrix_middle_top 
          shift: [-1.5kx, py/2]
        - ref: matrix_middle_top
          shift: [ px/2, py/2]
        - ref: matrix_inner_top
          shift: [-px/2 - kx/3, py/2]
        - ref: matrix_inner_top
          shift: [ 0,py/2]
        - ref: mirror_matrix_inner_top
          shift: [ 0,py/2]
        - ref: mirror_matrix_inner_top
          shift: [-px/2 - kx/3, py/2]
        - ref: mirror_matrix_middle_top
          shift: [ px/2 ,py/2]
        - ref: mirror_matrix_middle_top 
          shift: [-1.5kx, py/2]
        - ref: mirror_matrix_outer_top
          shift: [-px/2, py/2]
        - ref: mirror_matrix_outer_home
          shift: [-px/2,-py/2]
        - ref: mirror_matrix_pinky_bottom
          shift: [-px/2,-py/2]
        - ref: mirror_matrix_pinky_bottom
          shift: [px,-py/2]
        - ref: mirror_thumb_left
          shift: [-px/2, -py/2]
        - ref: mirror_thumb_middle
          shift: [px/2, -py/2]
        - ref: mirror_thumb_right
          shift: [-px/2, -py/2]
        - ref: mirror_thumb_right
          shift: [px, -py/2]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys