meta:
  engine: 4.1.0
  name: martlet
  author: Thomas Stephan

units:
  kx: cx
  ky: cy
  px: cx + 2
  py: cy + 2
  $default_width: cx
  $default_height: cy

points:
  key:
    padding: py
    spread: px

  zones.matrix:                                                                         
    rows:
      bottom:
      home:
      top:                            
    columns:
      outer:
        rows.bottom.skip: true
      pinky: 
        key.stagger: 0.5 cy
      ring:
        key.stagger: 7
      middle:
        key.stagger: 2
      index:
        key:
          stagger: -6
          #splay: -5
      inner:
        key:
          stagger: -3
          #splay: -10

  zones.thumb: 
    key:
      spread: px + 3  
    anchor:
      ref: matrix_middle_bottom
      shift: [0.5 cx,-cy - 12]
    columns:
      left:
      middle:
        key:
          splay: -12
          stagger: -3
      right:
        key:
          splay: -15
          stagger: -5
    
